#ifndef TMY_DEF_H
#define TMY_DEF_H

enum tmy_index_e {
	TMY_PARAM_ACCEPTED_PACKETS=0,
	TMY_PARAM_REJECTED_PACKETS,
	TMY_PARAM_LAST_OPCODE,
	TMY_PARAM_LAST_ERROR,
	TMY_PARAM_MODE,
	TMY_PARAM_SERVO1_CURR_POSITION,
	TMY_PARAM_SERVO1_TARGET_POSITION,
	TMY_PARAM_SERVO2_CURR_POSITION,
	TMY_PARAM_SERVO2_TARGET_POSITION,
	TMY_PARAM_SERVO3_CURR_POSITION,
	TMY_PARAM_SERVO3_TARGET_POSITION,
	TMY_PARAM_SERVO4_CURR_POSITION,
	TMY_PARAM_SERVO4_TARGET_POSITION,
	TMY_PARAM_LAST
};

#endif
